const catalogList = {
  rowWidth: 650,
  rowHeight: 64,
  rowGap: 7,
  listSlots: 4,
  contentTopOffset: 240,
  contentInsetX: 32,
  iconSize: 52,
  iconLeft: 48,
  textLeft: 96,
  textWidth: 420,
  buttonWidth: 108,
  buttonHeight: 42,
  buttonRight: 68,
  buttonBottom: 32,
  listPaddingBottom: 18,
  row: {
    fillColor: 0xf6dfad,
    lockedFillColor: 0xe5c98f,
    lockedAlpha: 0.84,
    strokeColor: 0x2a160a,
    strokeWidth: 3,
    radius: 8,
  },
  iconCard: {
    fillColor: 0xf9e8bf,
    lockedFillColor: 0xddc184,
    strokeColor: 0x3a210d,
    strokeWidth: 2,
    radius: 8,
  },
} as const

const catalogListHeight = catalogList.listSlots * catalogList.rowHeight + (catalogList.listSlots - 1) * catalogList.rowGap

const shopTabs = {
  width: 142,
  height: 40,
  gap: 8,
  yOffset: 160,
  radius: 8,
  strokeWidth: 3,
  inactiveFillColor: 0xe7b970,
  inactiveBorderColor: 0x291408,
  activeBorderColor: 0x1c1008,
} as const

export const ShopUIConfig = {
  iconButton: {
    size: 52,
    edgePadding: 18,
    fillColor: 0xf0d394,
    fillAlpha: 1,
    strokeColor: 0x2a160a,
    strokeWidth: 3,
    iconColor: 0x2a160a,
  },
  tabs: shopTabs,
  window: {
    width: catalogList.rowWidth + catalogList.contentInsetX * 2,
    height: catalogList.contentTopOffset + catalogListHeight + catalogList.listPaddingBottom,
    contentInsetX: catalogList.contentInsetX,
    backdropColor: 0x000000,
    backdropAlpha: 0.5,
    titleColor: '#fff0ce',
    subtitleColor: '#2d1a0b',
    cardColor: 0xe7b970,
    cardBorderColor: 0x2a160a,
    cardTextColor: '#2a160a',
    cardSubtextColor: '#2d1a0b',
    cardActiveColor: 0x5b8f34,
    cardLockedColor: 0xc1ad83,
    purchaseButtonColor: 0x5b8f34,
    purchaseButtonBorderColor: 0x1d1208,
    purchaseButtonDisabledColor: 0x5f5a51,
    purchaseButtonDisabledBorderColor: 0x1d1208,
    placeholderTextColor: '#6e5b36',
    frame: {
      radius: 18,
      railInset: 24,
      headerHeight: 94,
      footerHeight: 42,
      cornerSize: 58,
      boltRadius: 12,
      shadowColor: 0x000000,
      shadowAlpha: 0.35,
      outerWoodColor: 0x75451e,
      innerWoodColor: 0x9a632c,
      cornerColor: 0xa26830,
      outerStrokeColor: 0x1b0d05,
      outerStrokeWidth: 4,
      plankLineColor: 0x3b1e0c,
      plankLineAlpha: 0.35,
      boltColor: 0x8f8b7a,
    },
    parchment: {
      fillColor: 0xf4d99f,
      strokeColor: 0x2a160a,
      strokeWidth: 3,
      highlightColor: 0xfff2c9,
      highlightAlpha: 0.75,
      shadowColor: 0x3b1e0c,
      shadowAlpha: 0.28,
    },
    money: {
      width: 206,
      height: 42,
      coinRadius: 14,
      coinOuterColor: 0xd99a22,
      coinInnerColor: 0xf6c74e,
      coinStrokeColor: 0x3a210d,
      valueColor: '#287c2b',
    },
    buttons: {
      primary: {
        fillColor: 0x5b8f34,
        strokeColor: 0x1d1208,
        strokeWidth: 3,
        highlightColor: 0x9fca66,
        highlightAlpha: 0.55,
        radius: 6,
      },
      disabled: {
        fillColor: 0x5f5a51,
        strokeColor: 0x1d1208,
        strokeWidth: 3,
        highlightColor: 0xb5aca0,
        highlightAlpha: 0.35,
        radius: 6,
      },
      close: {
        fillColor: 0xf0d394,
        strokeColor: 0x2a160a,
        strokeWidth: 3,
        highlightColor: 0xfff0c5,
        highlightAlpha: 0.7,
        radius: 8,
      },
    },
  },
  catalogList: {
    ...catalogList,
    listHeight: catalogListHeight,
  },
} as const
